da-h/miniflask

src/miniflask/miniflask.py
This sets the default module to `info` and makes other modules optional, so that "empty" user modules can be supported.
=> Optional module loading and default module: info

README.md, src/miniflask/miniflask.py
This PR adds a `miniflask.run(call='main')` method, which calls the given event, if it is registered.
Using miniflask looks now a little bit cleaner.
```python
mf = miniflask(...)
mf.parse_args()
mf.run()
```
Additionally, the name of the event to call is passed as an argument `call`, so that it is easy to switch and execute other events, thus the generic `getattr(self.event, call)()` line.
=> Run method

src/miniflask/util.py
The white color often interferes with (dark) colorschemes that e.g. automatically invert colors. (I am not sure why the white color get's inverted to black and thus is not readable on dark background)
Here is the issue with a dark colorscheme terminal (in JetBrains PyCharm):
| issue | solved |
| --- | --- |
| ![miniflask_issue](https://user-images.githubusercontent.com/7113492/94686456-24c06e00-032b-11eb-8b9b-e198e6fcc197.png) | ![miniflask_issue_after](https://user-images.githubusercontent.com/7113492/94686703-7a951600-032b-11eb-9664-01341dd22297.png) |
This PR proposes to not highlight the text of `values` and therefire removes the white coloring.
Here is a quick comparison with a _default_ dark terminal:
| before | after |
| --- | --- |
| …
=> Remove white coloring of 'value' text

.flake8, .github/workflows/linting-python.yml
This PR updates the CI workflow for linting and splits jobs for the `src` and the `tests` folder.
In detail there are now the following jobs defined, which will run in the following order:
- **Syntax Check** for `src` using `flake8`
- **Static Analysis** for `src` using `flake8`
- `flake8` for `src`
- partially `pylint` for module `src/miniflask`
- complete `pylint` for `src/miniflask` (allowed to fail)
- **Syntax Check** for `tests` using `flake8`
- **Static Analysis** for `tests` using `flake8`
- `flake8` for `tests`
- partially `pylint` for all miniflask modules (`.module`) in `tests`
- complete `pylint` for all miniflask modules (`.module`) in `tests` (allowed to fail)
The previous workflow only implemented the *Syntax Check*, but no *Static Analysis*.
=> CI Workflow: Syntax Check and Static Analysis Improvements

src/miniflask/miniflask.py
This PR adds an argument `argv` (default: `None`) to the `run()` method to be able to pass command line arguments along.
Otherwise, command line arguments must be set via `sys.argv` which is not always a viable option (e.g. during tests).
The `run` method simply passes the `argv` variable to the `parse_args` method, which already has the option to receive arguments via the `argv` argument.
Therefore, backwards compatibility is given.
=> Add `argv` argument to `run()` method.

src/miniflask/miniflask.py
Only uses `sys.argv`, iff passed `argv` is `None`.
Otherwise, use passed list, or, if str is passed, split str by whitespace and use split list.
If unknown argument is passed, pass on no arguments at all.
=> Improve argument parsing with passed arguments.

src/miniflask/miniflask.py, src/miniflask/modules/modules/__init__.py, src/miniflask/modules/settings/__init__.py, tests/test_import/modules/otherdir/module2/__init__.py, tests/test_import/modules/parentdir/module1/__init__.py, tests/test_import/modules/parentdir/module2/__init__.py, tests/test_import/modules/parentdir/module3/__init__.py, tests/test_import/modules/parentdir/module3/submodule/__init__.py, tests/test_import/modules/parentdir/module4/__init__.py, tests/test_import/modules/parentdir/module5/__init__.py, tests/test_import/test_basic_import.py, tests/test_import/test_relative_import.py
This MR rewrites the way in which modules define inheritance.
In more Detail
Considering the `register` method of the module `a.b.c.d`.
Before this MR:
- `.addional` referenced `a.b.c.additional` (as typically one would use `.default` module constructs)
- `..` referenced `a.b`
- `.` referenced `a.b.c`
After this MR:
- `.addional` references `a.b.c.d.additional` (as we allow submodules now)
- `..` references `a.b.c`
- `.` is a noop.
=> Rework of module inheritance

.gitignore, src/miniflask/miniflask.py, tests/test_dynamic_state/miniflask, tests/test_import/modules/parentdir/module3/submodule/subsubmodule/__init__.py, tests/test_import/modules/parentdir/module3/submodule2/__init__.py, tests/test_import/modules/parentdir/module3/submodule_dir/submodule_with_folder_in_between/__init__.py, tests/test_import/modules/parentdir/module3/submodule_without_autoload/__init__.py, tests/test_import/test_parent_autoloading.py, tests/test_import/test_relative_import.py
This PR adds automatic loading of parent modules.
I.e. consider the defined modules:
- `parent`
- `parent2`
- `parent.level1`
- `parent.level1_second`
- `parent.level1.level2`
- `parent.level1.level2_second`
Loading `level2` will now load all modules that are direct parent modules of `level2`.
In this example `mf` will load (in the exact order):
- `parent`
- `parent.level1`
- `parent.level1.level2`
- implemented parent auto-loading as described above
- changes printing of loaded modules for the user. previously all parent modules would be listed one after another, together with the specific module (here `level1`). now, it will only list `parent.level1.level2`, but highlight `parent` and `level1` to show that these are modules themselves.
- to allow special cases where this behavior is not …
=> Parent autoload

src/miniflask/event.py, src/miniflask/miniflask.py, tests/test_event/miniflask, tests/test_event/modules/register_event_during_event/__init__.py, tests/test_event/test_register_event_during_event.py
This PR enables any event to itself append to existing events or even overwriting existing events.
To accomplish this, this PR does the following:
- `mf` (the same object as is used during `register(mf)` to the list of possible arguments that are automatically determined and passed to an event upon execution
- `mf.overwrite_event` to redefine previous definitions completely
- `mf.register_event` clears the cache of the `event`-object automatically
- adds a simple test case for event registration during an event
=> Dynamic Event Registration

src/miniflask/miniflask.py
Parent modules and relative module loading allows separating basic module behavior from specialized modules.
For instance, consider the module structure,
```
parent
parent.base
parent.child1
parent.child2
```
where each of the listed paths can be loaded by the user.
The intended behavior is to load `parent.base` in any case and let the user choose then between `child1` and `child2` as a specialized behavior.
This does already work.
However, if we want to define `parent` as a default choice of modules, (i.e. `child2`), if the user did not load any of the specializations him-/herself, auto loading of parents gets in the way.
In that case of loading `parent`, mf would load `parent.child2`. (works as intended)
In the chase of loading `parent.child1`, auto-loading would first load `parent` and …
=> added mf.any_child_loaded helper

src/miniflask/event.py, tests/beforeafter/modules/afterevent/__init__.py, tests/beforeafter/modules/afterevent2/__init__.py, tests/beforeafter/modules/beforeevent/__init__.py, tests/beforeafter/modules/beforeevent2/__init__.py, tests/beforeafter/modules/directcalls/__init__.py, tests/beforeafter/modules/setup/__init__.py, tests/beforeafter/test_beforeafter.py, tests/beforeafter/test_nonevent_beforeafter.py
This PR changes the way `before_eventname`/`after_eventname` events communicate with their caller (namely the event with the according name `eventname`.
**Attention**: This is a breaking change.
Reason for this change is that these kinds of events could not switch position (change execution from before to after or vice versa) and could not be used as a standalone without changing the function signatures. This PR solves this issue by improving the API of these events.
**API-Proposal**:
- Any `before_`/`after_` event gets called with a unique event object, that behaves just like the *normal* event object.
- This new event-object has a dict-attribute `.hook`
- **`before_`-events can read and manipulate** the function call arguments *before* the actual event will be called using …
=> Apichange beforeafter

src/miniflask/__init__.py, src/miniflask/event.py, src/miniflask/miniflask.py, tests/event/beforeafter/modules/afterevent2_multiple/__init__.py, tests/event/beforeafter/modules/afterevent_multiple/__init__.py, tests/event/beforeafter/modules/setup_multiple/__init__.py, tests/event/beforeafter/test_beforeafter_nonunique.py
This PR changes the way `before_eventname`/`after_eventname` events are called when using **non-unique** events.
**Attention**: This is a breaking change for events that assumed to wrap only single events to be wrapped.
Reason for this change is that the expected behavior for before/after events for a call such as `event.event_to_call(...)` is that they are called before/after that specific line **once**.
**What this PR does**:
- rewrite the call to hook before/after events just once before/after a list of non-unique events are called
- before events may transform `args` and `kwargs` just as for unique events
- after events may transform the list of results of the whore non-unique event list
- adaptions to the documentation to make this behavior clearer
- added also a note to the …
=> Api-change: single before after for non unique events

src/miniflask/event.py, tests/event/beforeafter/modules/afterevent/__init__.py, tests/event/beforeafter/modules/afterevent2/__init__.py, tests/event/beforeafter/modules/afterevent2_multiple/__init__.py, tests/event/beforeafter/modules/afterevent_multiple/__init__.py, tests/event/beforeafter/modules/setup_none_return/__init__.py, tests/event/beforeafter/test_beforeafter_none_return.py
This MR fixes #80 by specifying internally if the `eventCall` object given to the `before`/`after`-events get a return-value from the actual event.  
Before this MR, returning `None` was not possible in an event, when also registering an `after`-event, as that value was used internally to determine whether the `eventCall`-object is constructed with or without a return value in the event call stack.
- Added a helper-class `no_result_given` that gets overwritten any time an actual event (in contrast to a hook) gets called.
=> Return none in after event

src/miniflask/miniflask.py, tests/module_loading/modules/modules_b, tests/module_loading/modules_b, tests/module_loading/test_basic_import_dict.py
This MR solves a bug introduced in #83, where a module repository could not have a different id from its directory name.
MR #83 changed the way modules are loaded into `sys.modules` (see MR for more details).
However, the change introduced a bug when defining module directories using dict-notation in `mf.init`.
When defining a module-repository where the specified id differs from the actual folder it is imported from.
- Fixed the bug
- Added a test case for this scenario
=> Fix for new internal module loader

src/miniflask/miniflask.py, tests/event/overwrite_event/modules/main_overwrite_with_attached/__init__.py, tests/event/overwrite_event/modules/module1/__init__.py, tests/event/overwrite_event/test_overwrite_event.py
**Attention**: This is a breaking change.
This MR changes the way events are overwritten/redefined using `mf.unregister_event` or `mf.overwrite_event`.
By default, a call to any of the mentioned methods, all events of the given name are unregistered from miniflask (either only their function cache or any of their future uses), and also all events that are attached to the event to be changed.
A typical used-case, however is the transformation of events using other modules using `before_` and `after_` event hooks (attached events). With other words, replacing an event **should not** replace the hooks used to modify or inspect the calls when changing its function.
This MR thus, by default, keeps all attached events upon reregistration, but allows the user to remove all additional (typically) …
=> Keep attached events

docs/06-Predefined-Modules/index.md, src/miniflask/miniflask.py, src/miniflask/modules/__init__.py, src/miniflask/modules/definitions/__init__.py, src/miniflask/modules/settings/__init__.py, tests/argparse/required/test_argparse_required_types.py
- This MR improves debugging for missing CLI-variables by showing all definition locations when the error occurs.
- Additionally, the `[definition]` module is an extension of `[settings]` to show the location definitions together with the settings used
=> Show variable definiton locations for [definitions] and on CLI-argument error

src/miniflask/miniflask.py
**Api-Change**: This MR reenables `set_scope` to define the global id of a module.
Previously, `mf.set_scope(name)` would prefix the name with the module repository id the module is defined in.
It was not possible to adapt the scope of another repository.
After this MR, any module can share the scope with any other module.
(Related to #79)
=> mf: set_scope should set absoulte id (without repository base name)

src/miniflask/state.py, tests/state/temporary/modules/models/addingvariables/__init__.py, tests/state/temporary/modules/models/dosomething/__init__.py
This MR adapts the implementation of `state` to use python's ABC base classes instead of extending `dict`.
This change allows to iterate over the variables in a module.
```python
print("This module uses", len(state), "variables.")
for key in state:
print("This module is using the variable", key)
```
Some dict-operations could not be used on `state` variables (see #71).
This MR solves this by letting `collections.abc.MutableMapping` check if any functions are missing for a complete dict-implementation.
- derived `state` class from `MutableMapping`
- removed base class from `temporary_state` as it has never been used
- added unit tests to check for modules local dict-operations, like `iter(state)` and `len(state)`.
=> State using ABC base class

src/miniflask/state.py
**Attention**: This is may be a breaking change.
This MR removes `state.scope(...,local)` argument. Reason for this is that this functionality has been made obsolete due to fuzzy variable matching, introduced in miniflask `v2`.
=> Remove Unneeded state.scope(...,local) Argument

src/miniflask/event.py, src/miniflask/miniflask.py, tests/features/modules/a/__init__.py, tests/features/modules/b/__init__.py
#Replaced attached properties with hidden database 
**Attention**: This is a breaking change.
This MR changes the way miniflask saves data that relates to the wrapped event functions.
**Previously**:
- Wrapped events (functions or classes) were decorated with attributes that specify how the callables are used to construct the actual events
- Especially, when using classes this may lead to unexpected behavior 
To solve this, the `event` object now contains a hidden `_data` dictionary that saves this information.
**New Behavior**:
- `event._data[eventname]` contains the dictionary with all information required to construct the events
- `event._data[eventname]["modules"]`: list of modules that define the event `eventname`
- `event._data[eventname]["wrapped_event"]`: symlink to …
=> Replaced attached properties with hidden database

src/miniflask/miniflask.py, tests/argparse/required/modules/module1_with_error_message/__init__.py, tests/argparse/required/test_argparse_required_with_error_message.py
This MR allows the module-creator to give the user more information about a set of required variables (if they are missing).
Reason for this change is that miniflask allows module-groups to be entangled, in a way that require a module of one group to be loaded in order for another module to be working.
For instance, imagine a module to be a template or base-class for other instanciations that set the base variables according to their specialized features.
This MR gives the possibility to remind the user in such cases that there is such an dependency and the user requires to choose a specialization.
**Previously**:
The user would get a list of all required parameters, possibly not remembering or knowing about the inter-connection of some modules.
**New Behavior**:
Additionally, the user …
=> Predefined error messages

src/miniflask/miniflask.py, tests/argparse/optional/modules/module1/__init__.py, tests/argparse/optional/test_argparse_optional_types.py
This MR enables (or fixes `mf.optional` for) list types.
Miniflask did not allow to specify empty CLI-lists previously.
Using `mf.optional` this is now possible.
Not specifying the variable in CLI results in an empty list.
```python
def register(mf):
mf.register_defaults({
"variablelist": mf.optional([int])
})
```
=> Bugfix optional list type

src/miniflask/event.py, tests/event/named_call/modules/module1/__init__.py, tests/event/named_call/modules/module2/__init__.py, tests/event/named_call/test_named_call.py
This MR adds named calls to the event-object.
For non-unique events, the miniflask api has changed in earlier version.
Currently, in this case the call returns a list of 
```python
for module_id, result in event.named_call('myevent', the_argument=42).items():
print(f"Module with id {module_id} has returned", result)
```
=> event.named_call

src/miniflask/event.py, tests/event/register_event/test_event_exists.py
**Attention**: Using the event with the name `exists` is not possible anymore with this MR.
This MR adds the function `event.exists(event_name)` to each event object.
Instead of calling `event.optional.event_name` one might want to check if an event exists and proceed from there with different behavior.
**It can be used inside events as follows**:
```python
def some_event(event):
if event.exists("other_event"):
print("other_event exists")
```
**This can be also used for a more dynamic registration**:
```python
def register(mf):
if mf.event.exists("some_event"):
mf.register_event("some_event", lambda x: print("some_event called"))
```
=> event: added method event.exists(event_name)

src/miniflask/miniflask.py
**Attention**: This is a breaking change.
This MR implements a policy on the order of multiple realized `register_default_module`-calls.
Imagine, you register multiple default-modules: Each such calls checks for an event, and, if not registered, loads a given module and may overwrite its settings.  
**Setup**:
```
mf.register_default_module("module1", required_event="event1", overwrite_globals={
"var1": 42
})
mf.register_default_module("module2", required_event="event1", overwrite_globals={
"var1": 1337
})
mf.register_default_module("module1", required_event="event1", overwrite_globals={
"var1": 1234
})
mf.register_default_module("module2", required_event="event1", overwrite_globals={
"var1": 4321
})
```
**Problem**:
In case multiple such calls ask for the same event, the order has been …
=> Fix ambiguous register_default_module order

src/miniflask/__init__.py, src/miniflask/miniflask.py, tests/argparse/values/test_argparse_overwrites.py
This MR fixes an error due to a recent change in miniflask `v4.0`, given in MR #96.
The bug was that no boolean setting could be set anymore using the notation `--boolsetting`.
This MR fixes this issue and includes the missing unit test that should test against this kind of use.
=> Bugfix: CLI argument without value (i.e. a boolean setting) raises Exception

.github/workflows/linting-python.yml, src/miniflask/event.py, src/miniflask/miniflask.py
This MR fixes two small linter errors due to newer versions.
=> linter: fix errors by removing 'no-self-use'

src/miniflask/miniflask.py, src/miniflask/state.py
When defining default variables during `register()`, i.e. using `register_helpers`, it is possible to specify if callables are parsed to resolve variable chains using `register_helpers({...}, parsefn=False)`.
This MR adds a small QoL-Alias to include the same functionality into the variable definition itself, i.e.
instead splitting into two calls:
```
mf.register_helpers({
"var": lambda x: 42
})
mf.register_helpers({
"instance": MyClass()
}, parsefn=False)
```
this feature allows to merge such calls into a single one:
```
mf.register_helpers({
"var": lambda x: 42
"instance": mf.as_is_callable(MyClass())
})
```
=> mf.as_is_callable

src/miniflask/miniflask.py, src/miniflask/state.py
`mf.as_is_callable` have been introduced in #107.
Its goal is to allow helper variables to be set to classes.
By default, callable variables are expected to be dependency-functions that are called in the initialization phase of miniflask unless specified using `parsefn=False`.
This MR
- allows these callable variables defined using `mf.as_is_callable` to be used/called just as the class-instance it wraps
- by default sets `parsefn` to `False`. This effectively disables searching for dependency-chains for those classes, as this was the whole motivitaion for `mf.as_is_callable`
=> Bugfixes for new mf.as_is_callable feature

.github/workflows/pypi.yml
Until `v4.0.2` github releases have been triggered automatically.
As something in the toolchain has chaned since then, this MR readds this functionality using the official github action `actions/create-release`.
=> re-enable automatic github releases

src/miniflask/miniflask.py
This PR tries to import modules directly with the given module name/path if possible (assuming the module is a regular python module in the project).
Otherwise, the legacy code is run.
**Problem**:
Previously, serializing code, where miniflask modules are used, resulted in errors, since the import paths and names of the modules are changed (randomly).
**New Behavior**:
Now, if mf modules are actual python modules, a direct import is used.
=> Use direct import if possible, otherwise use legacy import.

.github/workflows/pypi.yml
Just a tiny PR: the github action for publishing to PyPI asks for fixing the action-branch to anything other than `master`.
Here, the `release/v1`-branch has been chosen.
=> github: fix warning from pypi action

tests/state/dependencies/modules/defarguments_module1/__init__.py
This PR adds a failing test case to the `v5-dev` branch.
The issue is that the registration method
```python
def register(mf):
mf.register_defaults({
"annotation": lambda: 10,
"annotation.bug": lambda: 10
})
```
succeeds for the first line registering `state["annotation"]`, but **fails for the second line registering `state["annotation.bug"]`.
**Merging this failing test because any further development of `v5` should fix this issue first.**
=> tests: add test against illegal-annotation bug

src/miniflask/state.py
This MR fixes the failing test introduced in #123.
**Problem**
was that the regex did not match any string, but only keys consisting of proper words (i.e. `"anyword"`).
**New Behavior**:
the new string-regex allows any string using `"[^"]*"` syntax instead. Also, this PR adds the possibility to use single quotation marks for the keys.
=> state: improve lambda regex, allowing any key name

.github/workflows/pypi.yml
Until now, this project uses githubs own action for creating new releases named `action/create-release`.
However, the [action is currently unmaintained, and the developers suggest using an alternative in the README.md](https://github.com/actions/create-release).
This PR also enables automatically generated release notes containing PRs and commits added in the respective release since the last one.
(Currently, one must click a button on the release page to generate the messages).
=> Move actions/create-release to softprops/action-gh-release
